<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-P7VKIKU" name="teste.Testar" tests="3" failures="0" timestamp="20 Apr 2018 20:52:23 GMT" time="3.864" errors="3">
  <testcase name="teste01" time="1.303" classname="teste.Testar">
    <error type="testlink.api.java.client.TestLinkAPIException" message="
The xml-rpc call to TestLink API method tl.reportTCResult failed.
Result[0] = {code=3030, message=Test Case (name=Primeiro/id=4) is not associated with Test Plan (name=test/id=2).}
">
      <![CDATA[testlink.api.java.client.TestLinkAPIException: 
The xml-rpc call to TestLink API method tl.reportTCResult failed.
Result[0] = {code=3030, message=Test Case (name=Primeiro/id=4) is not associated with Test Plan (name=test/id=2).}

	at testlink.api.java.client.TestLinkAPIClient.execXmlRpcMethodWithCache(TestLinkAPIClient.java:1209)
	at testlink.api.java.client.TestLinkAPIClient.reportTestCaseResult(TestLinkAPIClient.java:282)
	at testlink.api.java.client.TestLinkAPIClient.reportTestCaseResult(TestLinkAPIClient.java:246)
	at testlink.api.java.client.TestLinkAPIClient.reportTestCaseResult(TestLinkAPIClient.java:217)
	at teste.TestLinkConnection.updateResults(TestLinkConnection.java:19)
	at teste.Testar.sendResult(Testar.java:83)
	at teste.Testar.teste01(Testar.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.TestNG.privateMain(TestNG.java:1339)
	at org.testng.TestNG.main(TestNG.java:1308)
]]>
    </error>
  </testcase> <!-- teste01 -->
  <testcase name="teste02" time="1.301" classname="teste.Testar">
    <error type="testlink.api.java.client.TestLinkAPIException" message="
The xml-rpc call to TestLink API method tl.reportTCResult failed.
Result[0] = {code=3030, message=Test Case (name=Segundo/id=7) is not associated with Test Plan (name=test/id=2).}
">
      <![CDATA[testlink.api.java.client.TestLinkAPIException: 
The xml-rpc call to TestLink API method tl.reportTCResult failed.
Result[0] = {code=3030, message=Test Case (name=Segundo/id=7) is not associated with Test Plan (name=test/id=2).}

	at testlink.api.java.client.TestLinkAPIClient.execXmlRpcMethodWithCache(TestLinkAPIClient.java:1209)
	at testlink.api.java.client.TestLinkAPIClient.reportTestCaseResult(TestLinkAPIClient.java:282)
	at testlink.api.java.client.TestLinkAPIClient.reportTestCaseResult(TestLinkAPIClient.java:246)
	at testlink.api.java.client.TestLinkAPIClient.reportTestCaseResult(TestLinkAPIClient.java:217)
	at teste.TestLinkConnection.updateResults(TestLinkConnection.java:19)
	at teste.Testar.sendResult(Testar.java:83)
	at teste.Testar.teste02(Testar.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.TestNG.privateMain(TestNG.java:1339)
	at org.testng.TestNG.main(TestNG.java:1308)
]]>
    </error>
  </testcase> <!-- teste02 -->
  <testcase name="teste03" time="1.260" classname="teste.Testar">
    <error type="testlink.api.java.client.TestLinkAPIException" message="
The xml-rpc call to TestLink API method tl.reportTCResult failed.
Result[0] = {code=3030, message=Test Case (name=Terceiro/id=9) is not associated with Test Plan (name=test/id=2).}
">
      <![CDATA[testlink.api.java.client.TestLinkAPIException: 
The xml-rpc call to TestLink API method tl.reportTCResult failed.
Result[0] = {code=3030, message=Test Case (name=Terceiro/id=9) is not associated with Test Plan (name=test/id=2).}

	at testlink.api.java.client.TestLinkAPIClient.execXmlRpcMethodWithCache(TestLinkAPIClient.java:1209)
	at testlink.api.java.client.TestLinkAPIClient.reportTestCaseResult(TestLinkAPIClient.java:282)
	at testlink.api.java.client.TestLinkAPIClient.reportTestCaseResult(TestLinkAPIClient.java:246)
	at testlink.api.java.client.TestLinkAPIClient.reportTestCaseResult(TestLinkAPIClient.java:217)
	at teste.TestLinkConnection.updateResults(TestLinkConnection.java:19)
	at teste.Testar.sendResult(Testar.java:83)
	at teste.Testar.teste03(Testar.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.TestNG.privateMain(TestNG.java:1339)
	at org.testng.TestNG.main(TestNG.java:1308)
]]>
    </error>
  </testcase> <!-- teste03 -->
</testsuite> <!-- teste.Testar -->
